apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
  namespace: transactions
  labels:
    app: transactions-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      serviceAccountName: transactions-service-sa
      containers:
        - name: transactions-service
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/novabank/dev/transactions-service:${IMAGE_TAG}
          ports:
            - containerPort: 8003
          env:
            - name: SECRET_NAME
              value: "novabank/dev/rds/transactions"
            - name: AWS_REGION
              value: "${AWS_REGION}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 20
            periodSeconds: 20
